### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by xavierartot** [jseidl/GoldenEye#14]
Hi,
Thank you for your work.
I have an error here?
 
```
~ cd GoldenEye
~ pip install goldeneye.py
Collecting goldeneye.py
  Could not find a version that satisfies the requirement goldeneye.py (from versions: )
No matching distribution found for goldeneye.py
```

**Comment by jseidl** [comment]
Hi,

You don't need to pip install goldeneye itself.

You can just run ./goldeneye.py

If it complains or any dependency then you can install this dependency via
pip

Cheers,
Jan
