### ISSUE TITLE
Each attack is getting failed

### ISSUE THREAD

**Issue by techayu** [jseidl/GoldenEye#15]
Hello i am trying to ddos my own website which have simple html and every time it is giving this error
1381 GoldenEye strikes deferred. (0 Failed)
2279 GoldenEye strikes deferred. (0 Failed)
2779 GoldenEye strikes deferred. (0 Failed)
2779 GoldenEye strikes deferred. (0 Failed)
2779 GoldenEye strikes deferred. (0 Failed)
3279 GoldenEye strikes deferred. (0 Failed)
3779 GoldenEye strikes deferred. (0 Failed)
4279 GoldenEye strikes deferred. (0 Failed)
4779 GoldenEye strikes deferred. (0 Failed)
4779 GoldenEye strikes deferred. (0 Failed)
4779 GoldenEye strikes deferred. (0 Failed)
4779 GoldenEye strikes deferred. (0 Failed)
4779 GoldenEye strikes deferred. (0 Failed)

I even tried attacking on my local machine but still it is getting deffered each time.
Plz fix the script or tell me if i am wrong.

**Comment by jseidl** [comment]
Hi, I've changed the text, it should read "strikes hit" instead of "Deferred". Sorry about that. This log shows that the hits are being successful and 0 failed.
