### ISSUE TITLE
0 GolderEye strikes hit...Means my website is DDos free ?

### ISSUE THREAD

**Issue by ankitloud** [jseidl/GoldenEye#16]
I am getting this output... does it mean my application ddos free ?
0 GoldenEye strikes hit. (1902 Failed)
0 GoldenEye strikes hit. (3960 Failed)
0 GoldenEye strikes hit. (5948 Failed)
0 GoldenEye strikes hit. (7956 Failed)
0 GoldenEye strikes hit. (9936 Failed)
0 GoldenEye strikes hit. (11983 Failed)
0 GoldenEye strikes hit. (14054 Failed)
0 GoldenEye strikes hit. (16860 Failed)
0 GoldenEye strikes hit. (21502 Failed)
0 GoldenEye strikes hit. (44980 Failed)
0 GoldenEye strikes hit. (44985 Failed)
0 GoldenEye strikes hit. (61400 Failed)
0 GoldenEye strikes hit. (61415 Failed)
0 GoldenEye strikes hit. (61421 Failed)
0 GoldenEye strikes hit. (61444 Failed)
0 GoldenEye strikes hit. (61451 Failed)
0 GoldenEye strikes hit. (61455 Failed)
0 GoldenEye strikes hit. (61461 Failed)
0 GoldenEye strikes hit. (61464 Failed)

**Comment by jseidl** [comment]
Means the attacks are failing. (probably being dropped). The reasons may
vary.
