### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by rekojj** [jseidl/GoldenEye#21]
hello,
one of the most important things for ddosers is to be anonymous. please add proxy support ( socks preferred ). if the proxy support would be able to download proxy list from a free site would be very perfect. 

thanks.

**Comment by jseidl** [comment]
GoldenEye is not a tool intended for malicious use. It's a testing tool.

There's no included support for this kind of thing but is not hard to
implement it yourself.

Cheers

Jan Seidl

http://wroot.org
http://www.linkedin.com/in/janseidl


This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission. If verification is required please request a hard-copy
version.
