### ISSUE TITLE
RAM usage reach 100%

### ISSUE THREAD

**Issue by royryando** [jseidl/GoldenEye#22]
I just test my website using windows 10, 244GB RAM 32vCPUs.

**First test**
my command looks like:
`python goldeneye.py http://example.com -w 15 -s 150 -d`

This tool is really good, my website is taking a long time to respond even it use cloudflare, but my testing environment RAM usage is always increase until reach 100% and my env is not responding, maybe because the website isn't down so I try to test another website.

**Second test**
My command:
`python goldeneye.py http://example.com -w 15 -s 100 -d`
When RAM usage reach 16GB my website is down and I though this tools will idle, but why the RAM usage is always increase? is the worker/socket too high?

**Comment by jseidl** [comment]
Hi Roy,

The performance will be limited to your setup. Indeed more workers and
threads will use more CPU and memory until you run out of them.

Not saying that there couldn't be a bug in GoldenEye (leak). It definitely
could but so far I'm not aware of none.

Jan Seidl

http://wroot.org
http://www.linkedin.com/in/janseidl


This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. E-mail transmission cannot be
guaranteed to be secure or error-free as information could be intercepted,
corrupted, lost, destroyed, arrive late or incomplete, or contain viruses.
The sender therefore does not accept liability for any errors or omissions
in the contents of this message, which arise as a result of e-mail
transmission. If verification is required please request a hard-copy
version.
