### ISSUE TITLE
Doesn't work on Lightspeed servers?

### ISSUE THREAD

**Issue by theabhinavdas** [jseidl/GoldenEye#23]
Hey jseidl, I'm trying this on my own Lightspeed server running a Wordpress instance. However, I'm unable to take it down using GoldenEye if some basic Lightspeed firewall options are set. Am I doing something wrong with GoldenEye? Or is this the expected behavior?

**Comment by shaikhmanal** [comment]
Litespeed servers can handle such mass requests by caching it. So no need to worry, the tool works fine as described. Other tools with same method of GoldenEye will work the same way and won't take down Litespeed server because of it's ability to cache request and serve locally.

**Comment by jseidl** [comment]
There are a lot of mitigation nowadays that could thwart the tool. A single GoldenEye instance won't work if the server is well capable of handling abuse.
