### ISSUE TITLE
trying to strike on a vm running on esxi machine

### ISSUE THREAD

**Issue by ankitsinha121** [jseidl/GoldenEye#26]
GoldenEye v2.1 by Jan Seidl <jseidl@wroot.org>

Hitting webserver in mode 'post' with 1 workers running 10 connections each. Hit CTRL+C to cancel.
0 GoldenEye strikes deferred. (3104 Failed)
0 GoldenEye strikes deferred. (6244 Failed)
0 GoldenEye strikes deferred. (8975 Failed)
0 GoldenEye strikes deferred. (11629 Failed)
0 GoldenEye strikes deferred. (13790 Failed)
0 GoldenEye strikes deferred. (15103 Failed)
0 GoldenEye strikes deferred. (18050 Failed)
0 GoldenEye strikes deferred. (21120 Failed)
0 GoldenEye strikes deferred. (23663 Failed)
0 GoldenEye strikes deferred. (26920 Failed)

**Comment by jseidl** [comment]
There are several things that might be going on. Server-side blocking, connectivity issues, incorrect URL and such
