### ISSUE TITLE
Can i put a time limit in the attack . like it will run for 4 mins stop for 5 sec and again repeat?

### ISSUE THREAD

**Issue by refat2090** [jseidl/GoldenEye#30]
I am testing a server. So what happens is that when i launch the attack, the server gets down for 5 mins and then it becomes live . So if i then restart the attack the server again downs for 5 mins and then its up.I think the server restarts after 5 mins.

So i am trying to automate the start and stop of the attack.

**Comment by jseidl** [comment]
This is currently not possible. You can make a script to find out the pid and kill it after that given time.
