### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by staentomic** [jseidl/GoldenEye#5]
File "goldeneye.py", line 149
    print "Shutting down GoldenEye"
                                  ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by staentomic** [comment]
HELP

**Comment by jseidl** [comment]
Hi. You seem to be using python 3. Goldeneye is not ready yet for python 3.
Try using python 2 for this instead.

**Comment by staentomic** [comment]
Ok thank you

**Comment by smashudarkstar** [comment]
Hi, amazing program from what i see but with python 2.7.12 how do I add it to the system environment so, on cmd i can type python in and so it will not say not recognized ?

**Comment by jseidl** [comment]
Marking as resolved!
