### ISSUE TITLE
GoldenEye strikes deferred

### ISSUE THREAD

**Issue by NickVendetta** [jseidl/GoldenEye#7]
goldeneye  http://www.latihtubi.com -w 2

GoldenEye v2.1 by Jan Seidl <jseidl@wroot.org>

Hitting webserver in mode 'get' with 2 workers running 500 connections each. Hit CTRL+C to cancel.
0 GoldenEye strikes deferred. (258 Failed)
0 GoldenEye strikes deferred. (554 Failed)
0 GoldenEye strikes deferred. (890 Failed)
0 GoldenEye strikes deferred. (1125 Failed)
0 GoldenEye strikes deferred. (1409 Failed)
0 GoldenEye strikes deferred. (1769 Failed)
0 GoldenEye strikes deferred. (2213 Failed)
^CCTRL+C received. Killing all workers
Shutting down GoldenEye

**Comment by Tosible** [comment]
Either means the website is down, or they blocked your attacks

**Comment by metroyanno** [comment]
@Tosible, no, "Strikes Deffered" variable saying what number of strikes was blocked or crashed. In brackets says what number of connection timed out was responded (or responded error 500).

@NickVendetta, please, close issue.

**Comment by Anonymous2b** [comment]
looking for someone experienced in Layer7... please ereply

**Comment by HeroBrian389** [comment]
I have the same problem. I go after a simple webserver and I start to get 2000 failed

**Comment by Bryan1269** [comment]
I setup apache webserver on a Local Area Network.  The Apache Webserver's Machine is running Ubuntu 16.04. I ran goldeneye on another machine and set the Apache webserver IP and I got the same error. It states that all strike fails. Please do note that my webserver didn't run any firewalls or any DDOS protection. It only rans apache and PHP. Any ideas?

**Comment by jseidl** [comment]
That's weird. I didn't checked with latest versions in a while. Gonna setup
an environment and check to see if I can reproduce this bug

**Comment by HeroBrian389** [comment]
I'm running ubuntu 16.04 LTS and using anonsurf. I am running a couple of python pids and apache. I used to be able to take down websites but recently it won't work on even my own server. I check the website periodically from another ip and it's still up. I can't understand it. Any advice/help would be greatly appreciated.

**Comment by t0T4l5yN7h** [comment]
It works for me on most sights.  Especially lower end sites, However I am having trouble taking down an onion sight,  The first volley  hits with (0Fails) but every other volley fails and the server is not down.  I think maybe they block ip after the first volley.  Is there a tool that will work? maybe a dns amplified attack?

**Comment by jseidl** [comment]
It's hard to tell what's going on with the onion site. Should work
normally. Your hypothesis of being blocked after the first attack could be
true, unfortunately, there are many variables on which why it may fail that
I cannot conclude much

**Comment by Ranjeet20** [comment]
how to solve this error "0 GoldenEye strikes deferred. (258 Failed)"
