### ISSUE TITLE
Golden eye installing problem

### ISSUE THREAD

**Issue by hazeek** [jseidl/GoldenEye#8]
when i install the goldeneye.py,when i open new terminal and type ./goldeneye.py iit shows goldeneye.py command not found even if i put a url,it works when repeating the installation process

**Comment by metroyanno** [comment]
Write command, by you starting file and output to here

**Comment by lightpencil** [comment]
#While the thing is that it's only a file, no need for installing.

**Comment by hazeek** [comment]
Ok, but why my pc freezes?

**Comment by Tosible** [comment]
Probably too much for your computer to handle

**Comment by Ijlalh90** [comment]
i have same issues with freezes after sometime

**Comment by jseidl** [comment]
As Defalt said, this process is very resource intensive. Running in virtual
machines is not recommended.

Usually few workers and threads are needed for the attack to succeed. You
can tune them with the command line switches. Abuse of this values might
bring the system to an unusable state.

**Comment by jseidl** [comment]
Closing due inactivity
