### ISSUE TITLE
When trying to run 

### ISSUE THREAD

**Issue by nicemod666** [jseidl/GoldenEye#9]
When Trying to run i get this error tried everthing

Traceback (most recent call last):
  File "./goldeneye.py", line 44, in <module>
    import urlparse, ssl
  File "/usr/local/lib/python2.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: No module named _ssl

**Comment by metroyanno** [comment]
What is your OS?

**Comment by nicemod666** [comment]
Lunix

**Comment by metroyanno** [comment]
You installed "python2.7-dev"?

**Comment by nicemod666** [comment]
i have the latest python

Still won't Work even went thru the code for any errors and none ???????

**Comment by jseidl** [comment]
It seems your python's ssl library bindings are bad. Can you try in a
virtualenv or virtual machine?

**Comment by jseidl** [comment]
Closing due being a installation related issue
